name: Greetings

on: [issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for contributing to Redmine Issue Templates plugin!'' first issue'
        pr-message: 'Thanks you for contributing to Redmine Issue Templates plugin!'' first pr'
